// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table clusterhistory (NodeId:string, Address:string, Name:string, StartTime:datetime, IsAdmin:bool, MachineTotalMemory:long, MachineAvailableMemory:long, ProcessorCount:int, EnvironmentDescription:string, ProductVersion:string, Reserved0:int) 
